### ISSUE TITLE
ItemsRepeater Bug

### ISSUE THREAD

**Issue by dimthrak** [microsoft/Xaml-Controls-Gallery#775] opened 2021-09-18 12:31 UTC
The app crashes and closes when you do the operation below:

1. Go to 'Layout>ItemsRepeater'
2. Click on 'StackLayout - Horizontal' then 'StackLayout - Vertical'.

It was excpected to revert in vertical layout.

The app crashed then closed. I reopened it and when I did that operation, it did same.

- App downloaded from Store 
    -Version 1.2.21.0

Windows version:
- Windows 11 Build 22000.1

Device form factor:
- Desktop

**Comment by stmoy** [comment] 2021-09-20 18:16
I see this repro as well. Thank you for reporting this issue!

**Comment by chingucoding** [comment] 2021-09-20 18:54
The issue is actually an issue with the RadioButtons control, see https://github.com/microsoft/microsoft-ui-xaml/issues/3128. The code assumes that when selection changes the selection exists. In fact it is sometimes null and the app crashes. My hope was to wait for a WinUI fix instead of working around this.

**Comment by gregwoo-microsoft** [comment] 2022-01-07 19:24
Hey @dimthrak! :) We fixed this in the latest version of the XCG. Feel free to let us know if you are still experiencing this bug. I'll close this issue in the meantime.

**Closed by gregwoo-microsoft** 2022-01-07 19:24 UTC
Labels: bug
