### ISSUE TITLE
ItemsRepeater controls have useless scrollbar

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#615] opened 2020-12-17 11:46 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/51363864/102483920-9a7ddf80-40b9-11eb-91c0-e5cfecb69a11.png)

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.) 0.2.17.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment] 2020-12-17 13:20
Not sure what the issue is. The content might need a scrollbar and it seems that you have enabled the "always show scrollbar" option looking at the settings item which also has a scrollbar.

**Comment by Poopooracoocoo** [comment] 2020-12-17 13:26
@chingucoding what do you mean? I definitely have the always show scrollbars option enabled. There's nothing there to scroll, so I don't understand why there is a scrollbar. If there is something to scroll, then there would be a scrollbar, right?

**Comment by chingucoding** [comment] 2020-12-17 13:29
In it's initial configuration there is nothing to scroll, yes. But you can add items to the sample in which case the sample needs scrolling:
![Image showing basic ItemsRepeater sample](https://user-images.githubusercontent.com/16122379/102493974-4270ba00-4074-11eb-91d6-b78e3a98c009.png)

**Comment by Poopooracoocoo** [comment] 2020-12-17 13:45
another weird thing is that the scrollbar overlaps the items

**Comment by stmoy** [comment] 2020-12-17 23:49
> I definitely have the always show scrollbars option enabled.
> There's nothing there to scroll, so I don't understand why there is a scrollbar. If there were something to scroll, then there would be a scrollbar, right?

Always showing scrollbars will always show the scroll bars, even if there is nothing to scroll. @chingucoding is correct to point out that this scrollbar exists because there _can_ be extra items that cause a scroll. With the "always show scrollbars" option disabled, the scrollbar hides when it is not needed. 

> another weird thing is that the scrollbar overlaps the items

This part is "by design"; the scrollbars throughout Windows overlay the content. Some apps build in padding to offset the scrollbar occluding, but not all do. In this case, this is the default "by design" behavior, not something the Gallery is specifically doing. 

-=-=-

This all seems "by design" to me.

**Comment by Poopooracoocoo** [comment] 2020-12-18 01:46
@stmoy 
>Always showing scrollbars will always show the scroll bars, _even if there is nothing to scroll_

WHAAAAT?? I had no idea. Then that Windows setting isn't what I want if that's what it's meant to do. I just want to restore the pre-1803 behaviour where scrollbars weren't annoying to use. 

Websites in browsers don't have empty scrollbars and content will readjust for when the scrollbar appears. See like any codepen, like this one: https://codepen.io/valhead/pen/adnKt Then again, browsers don't have these stupid disappearing scrollbars. 

>This part is "by design"; the scrollbars throughout Windows overlay the content

Seriously? Overlapping is by design? Even when that Windows setting is enabled? Are you _sure_?

**Comment by stmoy** [comment] 2020-12-18 19:22
> I just want to restore the pre-1803 behaviour where scrollbars weren't annoying to use.

This is good feedback, but not for the Gallery. Please consider opening an issue on the microsoft-ui-xaml repo. 

> Seriously? Overlapping is by design? Even when that Windows setting is enabled? Are you sure?

Yes indeed: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/scroll-controls

>> _When the scrollbar is visible it is overlaid as 16px on top of the content inside your ScrollViewer. In order to ensure good UX design you will want to ensure that no interactive content is obscured by this overlay. Additionally if you would prefer not to have UX overlap, leave 16px of padding on the edge of the viewport to allow for the scrollbar._

**Comment by Poopooracoocoo** [comment] 2020-12-19 02:07
>>I just want to restore the pre-1803 behaviour where scrollbars weren't annoying to use.
>
>This is good feedback, but not for the Gallery. Please consider opening an issue on the microsoft-ui-xaml repo.

Who will then direct me to the void that is the feedback hub. >.> 

surprise, surprise. shitty windows setting doesn't do what I, or a bunch of people thought. 🙄

**Comment by Felix-Dev** [comment] 2020-12-30 12:04
Isn't this just an issue with the VerticalScrollbarVisibility not being set to `Auto` for the ScrollViewer used in the XCG sample? By default, the VerticalScrollBarVisibility is set to "Visible" which explains why it shows up even if there is currently no content to scroll.

Even with the setting "Automatically hide scrollbars in Windows" turned on (I did not find an option named "always show scrollbars"), if the Horizontal/VerticalScrollBarVisibility is not changed from the default value, we can make the scrollbar show up when there is no content. See for example https://github.com/microsoft/microsoft-ui-xaml/issues/3771 (it's replicable here too),

I expect if the VerticalScrollBarVisibility is set to "Auto", then the scrollbar won't show up if there is no content to scroll, even if "Automatically hide scrollbars in Windows" is turned off.

**Comment by stmoy** [comment] 2021-01-04 21:17
@Felix-Dev - very clever! I tried out that hypothesis and confirmed that setting the VerticalScrollbarVisibility to Auto does indeed fix this issue. 

Reopening this issue so I can close it with a fix.

**Closed** 2021-01-04 21:47 UTC
