### ISSUE TITLE
TeachingTip flyout occludes text on 2nd, 3rd, etc. open.

### ISSUE THREAD

**Issue by scottdsanders** [microsoft/Xaml-Controls-Gallery#400] opened 2020-04-08 23:15 UTC
**Describe the bug**
When re-opening a teaching tip for the 2nd, 3rd, or more times, some portion of the title or subtitle text will be cut off.

**Steps to reproduce the bug**
1. Launch XAML Controls Gallery app v1.2.13.0
2. Select Dialogs and Flyouts from the left pane
3. Select TeachingTip
4. From the top example, select "Show TeachingTip"
5. Observe text is all visible
6. Dismiss the tip window
7. Reselect "Show TeachingTip"
8. Notice now that some text is occluded.

Note: I discovered this in my own app but it was easier to show that this is also failing in the XAML Controls Gallery app.

**Expected behavior**
Title and Subtitle text should always be visible even if a TeachingTip is reopened.

**Actual behavior**
Some of either the Title or Subtitle text is cut off because the window is too small.

**Screenshots**

![image](https://user-images.githubusercontent.com/26178243/78842104-f97c4800-79b3-11ea-92d2-9bc639c3750c.png)

**Version Info**
XAML Controls Gallery app v1.2.13.0
Windows 1909 (18363.720)

Gallery version (found on Settings page): 
1.2.13.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment] 2020-04-08 23:33
Thank you for filing this issue. This is a dupe of the following TeachingTip bug: https://github.com/microsoft/microsoft-ui-xaml/issues/1372

**Closed by stmoy** 2020-04-08 23:33 UTC
