### ISSUE TITLE
TabView sample: cannot rearange tabviewItems

### ISSUE THREAD

**Issue by roonius** [microsoft/Xaml-Controls-Gallery#501] opened 2020-07-13 13:31 UTC
**Describe the bug**
TabView sample cannot rearange tabviewItems

**Steps to reproduce the bug**
Run the gallery, look for tabview.
Try to rearange tabviewitems. 
Prohibition sign appears and one cant move the item to different location.

**Expected behavior**
TabViewItem relocates

**Comment by stmoy** [comment] 2020-07-14 00:22
@roonius, thank you for filing this issue. I am not able to reproduce it (I can rearrange the tabs) in the Store version of the app. Can you provide more information please? 

Specifically, which version of the app are you running (version found in app settings)? Is this from the Store or built from the master branch on GitHub? Which sample within the TabView page are you trying?

**Comment by roonius** [comment] 2020-07-14 09:44
I built from the master branch:
![image](https://user-images.githubusercontent.com/7190183/87410744-5d279a00-c5cf-11ea-93ea-48bc550163bb.png)

On all tabitems i get "not allowed" sign when trying to drag/relocate tab:
![image](https://user-images.githubusercontent.com/7190183/87410991-b68fc900-c5cf-11ea-91da-f6e54db6aa94.png)

**Comment by stmoy** [comment] 2020-07-14 17:16
Ah! Thank you for the clarification. 

This specific sample is currently broken pending a framework fix that will go into WinUI 2.5 - https://github.com/microsoft/microsoft-ui-xaml/pull/2634

Do the other samples on this page work ok for you?

**Comment by stmoy** [comment] 2020-07-14 17:33
Oh, interesting. You're also running the WinUI 3.0 version of the Gallery. CC: @MikeHillberg will changes from 2.5 get ported into 3?

**Comment by MikeHillberg** [comment] 2020-07-14 17:47
Yes but it's not there yet. WinUI3/Preview2 will include WinUI2.4.

**Comment by stmoy** [comment] 2020-07-16 18:36
I have verified that this issue is fixed in the `master` branch of the Xaml Controls Gallery. The fix will take some time to propagate to the other endpoints (like the Store version and the WinUI 3.0 Preview version) but it is expected to get to all of those endpoints eventually - so I'm going to close this issue.

**Closed by stmoy** 2020-07-16 18:36 UTC

**Comment by roonius** [comment] 2020-07-17 10:15
Thank you @stmoy
