### ISSUE TITLE
 navigating to a control from the AutoSuggestBox doesn't change the navigation category you're in

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#437] opened 2020-05-19 17:27 UTC
**Describe the bug**

 navigating to a control from the AutoSuggestBox doesn't change the navigation category you're in

**Steps to reproduce the bug**

1. Open XAML Controls Gallery
2. Type in "button"
3. Navigate to the Button control.

**Expected behavior**

App would move to the Button page in the Basic Input tab 

**Actual behavior**

XAML Controls Gallery remains on What's New page.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment] 2020-05-19 21:08
This is a duplicate of #420 .

**Closed** 2020-05-20 04:31 UTC
