### ISSUE TITLE
ListView Drag Animation sending random item to the top

### ISSUE THREAD

**Issue by hawkerm** [microsoft/Xaml-Controls-Gallery#452] opened 2020-05-26 05:34 UTC
**Describe the bug**
When dragging an item in the the left-hand list, it's causing a lower item to fly all the way through the list to the top. (Maybe this is a ListView bug?)

**Steps to reproduce the bug**

1. Go to ListView sample
2. Go to Drag/Drop/Reordering sample
3. Drag an item from right-hand-side to the left-hand side
4. Wait for gap to appear

**Actual behavior**
Lower item goes flying all the way to the top and out of view. (Seems more pronounced when dragging to the top of the left-side list.)

**Expected behavior**
Only items separate to make space for the new item, no other items move.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment] 2020-06-05 11:30
Looking at the source code of that sample, it doesn't seem like that we are doing anything special. This is probably an issue with the underlying animation I think and not the sample in the XAML Controls Gallery.

**Comment by stmoy** [comment] 2020-06-05 20:20
CC: @anawishnoff - can you take a look at this and let us know if we should redirect to the WinUI repo?

**Comment by anawishnoff** [comment] 2020-06-05 20:45
Thanks! This bug is being tracked at #409. Some more investigation is needed to figure out if it's a bug with the sample or a bug with the platform. However, upon my initial investigation of the bug it seemed more like a bug with the sample itself, as I found that this weird animation only occurs when dragging from the right list into the left list.

**Comment by stmoy** [comment] 2020-06-05 20:50
Thanks Ana. Closing this as a dupe of #409.

**Closed by stmoy** 2020-06-05 20:50 UTC
