### ISSUE TITLE
Determinate progress ring doesn't go to 99%

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#616] opened 2020-12-17 11:50 UTC
**Describe the bug**

![IDYb1I96Bt](https://user-images.githubusercontent.com/51363864/102484444-66ef8500-40ba-11eb-8b66-d95c029f5711.gif)

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.) 0.2.17.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

and when the progress ring is at 100% it looks weird

**Comment by stmoy** [comment] 2020-12-17 23:55
CC: @MarissaMatt - is this an issue with the Gallery or the ring? It seems like an issue with the ring to me. 💍

**Comment by stmoy** [comment] 2020-12-17 23:57
Dupe of: https://github.com/microsoft/microsoft-ui-xaml/issues/3787

**Closed by stmoy** 2020-12-17 23:57 UTC
