### ISSUE TITLE
Empty scrollbars appear next to footers in NavigationViews

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#614] opened 2020-12-17 11:37 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/51363864/102483077-53dbb580-40b8-11eb-8c94-5f692c04d2a4.png)

**Steps to reproduce the bug**

1. open app

**Expected behavior**

no scrollbar

**Actual behavior**

scrollbar 

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.) 0.2.17.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by Poopooracoocoo** [comment] 2020-12-17 11:37
Actually see https://github.com/microsoft/microsoft-ui-xaml/issues/3771

**Comment by stmoy** [comment] 2020-12-17 23:59
The gallery isn't doing anything special here, dupe of microsoft/microsoft-ui-xaml#3771

**Closed by stmoy** 2020-12-17 23:59 UTC
