### ISSUE TITLE
CommandBar when on top expand to top

### ISSUE THREAD

**Issue by mklemarczyk** [microsoft/Xaml-Controls-Gallery#367] opened 2020-03-01 21:59 UTC
**Describe the bug**
CommandBar when on top expand to top instead down, so some content is clipped.

**Steps to reproduce the bug**
1. Go to AppBarButton
2. Click on '...' button in page header

**Expected behavior**
CommandBar expand to show buttons labels in direction to down.

**Actual behavior**
CommandBar expand to show buttons labels in direction to up.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by YuliKl** [comment] 2020-03-02 03:54
@mklemarczyk can you provide a screenshot showing the problem? Is this an issue in the Controls Gallery app or a different app?

**Comment by mklemarczyk** [comment] 2020-03-10 16:16
I believe that the bug is both in Controls Gallery app and control itself.
The behavior is wrong in Controls Gallery app. As well I did not managed to configure the CommandBar in simple application to expand in direction to down.

The CommandBar seems to expand always up unless the CommandBar top edge is a window top edge. It seems to do not consider that CommandBar control can be located in top of the container that does not share top edge with window.

Like for example in attached screenshot.
![app-bar-button-example](https://user-images.githubusercontent.com/2727261/76334057-d1d18b80-62f2-11ea-8240-a2b8a5416a2a.png)

**Comment by YuliKl** [comment] 2020-03-10 19:31
> The CommandBar seems to expand always up unless the CommandBar top edge is a window top edge.

I believe you're seeing expected behavior as described in our documentation: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars#open-and-closed-states

In your original issue description you mentioned content clipping. Do you actually see content get clipped, or are you speculating that it might?

I'm closing this issue for now because I believe everything you're seeing is by design. Please reopen with a screenshot showing clipping or other problems that a user might encounter.

**Closed by YuliKl** 2020-03-10 19:31 UTC
