### ISSUE TITLE
XAML Controls Gallery goes back to What's New page when it is suspended and resumed

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#537] opened 2020-08-21 12:45 UTC
**Describe the bug**

**Steps to reproduce the bug**

1. Open XAML Controls Gallery
2. Go to Button page
3. Minimise
4. Maximise 

**Expected behavior**

App would be on the button page

**Actual behavior**

App is back to home page and you must press the back button to get back to it.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.16.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment] 2020-08-29 08:17
I'm having trouble reproing this, even if the XAML Controls Gallery is suspended (at least according to Taskmanager it was).

**Comment by Poopooracoocoo** [comment] 2020-08-29 09:45
In my case it was instantaneous but I was also low on memory at the time as I had many Chrome windows (with extensions), Word windows, an Excel document, an Adobe Acrobat Reader window and an Electron app. It was actually only Chrome and that Electron app that were hogging the memory as you could guess. 

Settings usually takes much longer for this to happen under the same circumstances though. I don't use many UWP apps so I don't know if it also happens there. ~~Photos and Movies & TV make UWP and WinUI look really bad lol~~

Funnily enough, I can't repro it right now and I have the same apps open. I tried leaving it minimised for a while and still couldn't repro it

**Comment by stmoy** [comment] 2020-09-01 22:35
Hmm. Since we can't seem to repro, closing this issue as "no repro".

**Closed by stmoy** 2020-09-01 22:35 UTC

**Comment by Poopooracoocoo** [comment] 2020-09-02 02:19
but this sometimes also happens to Settings. it could be a uwp wide problem. i tend to leave the bluetooth page open so i can quickly switch from listening on my phone to my laptop.

**Comment by stmoy** [comment] 2020-09-02 16:46
> but this sometimes also happens to Settings. it could be a uwp wide problem. i tend to leave the bluetooth page open so i can quickly switch from listening on my phone to my laptop.

If it is a general UWP issue, it'd be more appropriate to reopen in either the WinUI repo or the Project Reunion repo.

**Comment by Poopooracoocoo** [comment] 2020-09-03 05:24
can't tell if you're joking

**Comment by stmoy** [comment] 2020-09-03 15:56
> can't tell if you're joking

Not joking 😅 -  Since this issue doesn't seem to be specific to the XCG, and since we can't repro even in the XCG, the issue should be redirected to another repo where it might get traction (like the WinUI repo or the Project Reunion repo). But it looks like you've already filed one on Project Reunion - thanks!

**Comment by Poopooracoocoo** [comment] 2020-09-03 21:25
two issues about the design got closed and then ignored in the calculator repo and then another one got closed and then ignored in the project reunion repo. i got burned lol. ooh and then there's me complaining a ton about windows. one of those was in the winui repo, about shadows not being a separate toggle to transparency.

**Comment by maxkatz6** [comment] 2020-09-03 22:03
Steps to reproduce:
1. Open application from VS
2. Navigate to any specific page
3. Invoke "Suspend and shutdown" from "Lifecycle events".
4. Launch application again without rebuild (it will remember previous state as Terminated).
5. See that state wasn't restored.

I believe that SuspensionManager class doesn't do its job - it saves state on Suspended, but RestoreAsync method doesn't make any effect.

If I understand correctly, in latest Windows versions application can be suspended with ability to completely restore by OS itself. In that case OnActivated method is not even called!
But in some rare cases, that is hard to reproduce, it works in exact way as it worked on mobile devices - restore is managed by application, and OnActivated is called with PreviousExecutionState == ApplicationExecutionState.Suspended, that doesn't work in XamlControlsGallery.

**Comment by maxkatz6** [comment] 2020-09-03 22:05
And EnsureWindow method should handle Suspended state as well.
https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/App.xaml.cs#L139

@stmoy I believe there is an issue in Xaml-Controls-Gallery, so it could be reopened.
Although I am not familiar with codebase, I hope my little research can help someone.
